<?php
/**
 * 🛠️ Setup Script for Unified Bot Platform
 * Configure webhook and test bot connectivity
 */

echo "╔════════════════════════════════════════════════════════════╗\n";
echo "║      🤖 Unified Bot Platform - Setup Wizard               ║\n";
echo "╚════════════════════════════════════════════════════════════╝\n\n";

// Check PHP version
if (version_compare(PHP_VERSION, '7.4', '<')) {
    echo "❌ PHP 7.4+ required. Current: " . PHP_VERSION . "\n";
    exit(1);
}
echo "✅ PHP Version: " . PHP_VERSION . "\n";

// Check curl
if (!extension_loaded('curl')) {
    echo "❌ cURL extension not found\n";
    exit(1);
}
echo "✅ cURL extension found\n";

// Check write permissions
$data_dir = __DIR__ . '/data';
if (!is_dir($data_dir)) {
    if (!mkdir($data_dir, 0755, true)) {
        echo "❌ Cannot create data directory\n";
        exit(1);
    }
}

if (!is_writable($data_dir)) {
    echo "❌ data/ directory is not writable\n";
    echo "Run: chmod -R 755 data/\n";
    exit(1);
}
echo "✅ data/ directory writable\n";

$child_dir = $data_dir . '/child_bots';
if (!is_dir($child_dir)) {
    mkdir($child_dir, 0755, true);
}
echo "✅ child_bots/ directory ready\n\n";

// Read configuration
echo "📝 Configuration Setup\n";
echo "───────────────────────────────────────────────────────────\n\n";

echo "Enter your BOT_TOKEN (Master Bot from @BotFather): ";
$bot_token = trim(fgets(STDIN));

if (empty($bot_token)) {
    echo "❌ Token cannot be empty\n";
    exit(1);
}

echo "Enter your Telegram ID (Admin ID): ";
$admin_id = trim(fgets(STDIN));

if (!is_numeric($admin_id)) {
    echo "❌ Admin ID must be numeric\n";
    exit(1);
}

echo "Enter build cost in coins (default 50): ";
$build_cost = trim(fgets(STDIN));
$build_cost = empty($build_cost) ? 50 : (int)$build_cost;

echo "Enter your domain (e.g., example.com): ";
$domain = trim(fgets(STDIN));

if (empty($domain)) {
    echo "❌ Domain cannot be empty\n";
    exit(1);
}

// Add https if not present
if (strpos($domain, 'http') !== 0) {
    $domain = 'https://' . $domain;
}

// Test bot token
echo "\n🧪 Testing Bot Token...\n";
$ch = curl_init();
curl_setopt($ch, CURLOPT_URL, "https://api.telegram.org/bot$bot_token/getMe");
curl_setopt($ch, CURLOPT_RETURNTRANSFER, true);
$response = curl_exec($ch);
curl_close($ch);

$result = json_decode($response, true);
if (!$result['ok']) {
    echo "❌ Invalid bot token\n";
    exit(1);
}

$bot_username = $result['result']['username'];
echo "✅ Bot verified: @$bot_username\n\n";

// Setup webhook
echo "⚙️  Setting up Webhook...\n";
$webhook_url = "$domain/bot_unified.php";
echo "Webhook URL: $webhook_url\n";

$ch = curl_init();
curl_setopt($ch, CURLOPT_URL, "https://api.telegram.org/bot$bot_token/setWebhook");
curl_setopt($ch, CURLOPT_POST, true);
curl_setopt($ch, CURLOPT_POSTFIELDS, http_build_query(['url' => $webhook_url]));
curl_setopt($ch, CURLOPT_RETURNTRANSFER, true);
$response = curl_exec($ch);
curl_close($ch);

$result = json_decode($response, true);
if (!$result['ok']) {
    echo "❌ Failed to set webhook: " . ($result['description'] ?? 'Unknown error') . "\n";
    exit(1);
}
echo "✅ Webhook configured successfully\n\n";

// Create configuration file
echo "💾 Saving Configuration...\n";
$config = <<<PHP
<?php
// ⚙️ Unified Bot Platform Configuration
// Generated by setup script at " . date('Y-m-d H:i:s') . "

define('BOT_TOKEN', '$bot_token');
define('ADMIN_ID', $admin_id);
define('DATA_DIR', __DIR__ . '/data');
define('CHILD_BOTS_DIR', DATA_DIR . '/child_bots');
define('BUILD_COST', $build_cost);
define('WEBHOOK_URL', '$webhook_url');

// These should be included in bot_unified.php
?>
PHP;

file_put_contents(__DIR__ . '/config.php', $config);
echo "✅ Configuration saved to config.php\n\n";

// Summary
echo "╔════════════════════════════════════════════════════════════╗\n";
echo "║                  ✅ Setup Complete!                        ║\n";
echo "╚════════════════════════════════════════════════════════════╝\n\n";

echo "📋 Configuration Summary:\n";
echo "───────────────────────────────────────────────────────────\n";
echo "Bot Username:     @$bot_username\n";
echo "Admin ID:         $admin_id\n";
echo "Build Cost:       $build_cost coins\n";
echo "Webhook URL:      $webhook_url\n";
echo "Data Directory:   $data_dir\n\n";

echo "🚀 Next Steps:\n";
echo "───────────────────────────────────────────────────────────\n";
echo "1. Send /start to @$bot_username\n";
echo "2. Create your first bot\n";
echo "3. Test file upload functionality\n";
echo "4. Read BOT_UNIFIED_GUIDE.md for detailed instructions\n\n";

echo "📚 Documentation:\n";
echo "───────────────────────────────────────────────────────────\n";
echo "- BOT_UNIFIED_GUIDE.md - Complete user guide (Persian)\n";
echo "- bot_unified.php      - Main bot file (1127 lines)\n\n";

echo "✅ Platform is ready to use!\n";
?>
