<?php
/**
 * Builds the single-file version:  php tools/build.php [outDir]
 * Output: <outDir>/bot.php (all code) + <outDir>/config.php (settings template).
 * Upload both files to the same folder; fonts are downloaded on first run.
 */
if (PHP_SAPI !== 'cli') {
    exit('CLI only');
}
$root = dirname(__DIR__);
$out = $argv[1] ?? $root . '/dist';
if (!is_dir($out)) {
    mkdir($out, 0775, true);
}

$strip = static function (string $code): string {
    $code = preg_replace('/^<\?php\s*/', '', $code);
    return trim(preg_replace('/^declare\(strict_types=1\);\s*/m', '', $code));
};

$parts = [];

// 1) bootstrap (global functions) with paths relative to bot.php
$boot = $strip(file_get_contents("$root/src/bootstrap.php"));
$boot = str_replace("define('APP_ROOT', dirname(__DIR__));", "define('APP_ROOT', __DIR__);", $boot);
$boot = preg_replace('/spl_autoload_register\(.*?\n\}\);\n/s', '', $boot);
$parts[] = "namespace {\n\n$boot\n\n}";

// 2) default brain weights
$brain = $strip(file_get_contents("$root/brain/strategy.php"));
$parts[] = "namespace {\n\nfunction app_brain_default(): array\n{\n$brain\n}\n\n}";

// 3) every class, wrapped in a braced namespace block
$files = new RecursiveIteratorIterator(new RecursiveDirectoryIterator("$root/src", FilesystemIterator::SKIP_DOTS));
$classes = [];
foreach ($files as $f) {
    if ($f->getExtension() === 'php' && $f->getFilename() !== 'bootstrap.php') {
        $classes[] = $f->getPathname();
    }
}
sort($classes);
foreach ($classes as $file) {
    $code = $strip(file_get_contents($file));
    if (!preg_match('/^namespace\s+([^;]+);/m', $code, $m)) {
        fwrite(STDERR, "No namespace in $file\n");
        exit(1);
    }
    $code = preg_replace('/^namespace\s+[^;]+;/m', '', $code, 1);
    $parts[] = "namespace {$m[1]} {\n\n" . trim($code) . "\n\n}";
}

// 4) entry point
$main = $strip(file_get_contents("$root/tools/bundle_main.php"));
$parts[] = "namespace {\n\n$main\n\n}";

$header = "<?php\n/**\n * Analyst bot - single-file build (generated by tools/build.php, do not edit by hand).\n"
    . " * Upload together with config.php. Webhook URL = the address of this file.\n"
    . " * Setup in the browser: https://your-domain/path/bot.php?setup=<webhook_secret>\n */\n\ndeclare(strict_types=1);\n\n";
file_put_contents("$out/bot.php", $header . implode("\n\n", $parts) . "\n");
if (!is_file("$out/config.php")) {
    copy("$root/config.example.php", "$out/config.php");
}
echo "Built $out/bot.php (" . round(filesize("$out/bot.php") / 1024) . " KB)\n";
